"""The server-side DOM: the harness's own copy of the artboard document.

The op vocabulary is deliberately DOM-shaped so the harness can apply it with
Python's html.parser plus a small serializer — no browser, no lxml. The iframe
is a view; this module is the document. Every op — the model's edit tools, the
page's inspector, a drag in the iframe — lands here first, and the page is told
to re-render from the result. If a selector misses here, the op is refused
exactly as the page would refuse it: one validation path, two front ends.

Selectors are element-index paths (e.g. `0>1>2`), generated by the in-iframe
script and resolvable here: each segment is the index among that parent's
element children, counting from the document root — `<html>` is `0`, and
`<body>` is `0>1` in a document that has a `<head>`. They are stable within a
version and deliberately NOT stable across a regenerate — a regenerate lands
as a new version with fresh selectors.

What this module deliberately does not know: computed style. The harness stores
the op that produced a layout; the numbers in the inspector come from the
iframe's getBoundingClientRect. Layout is always measured in the view, never
stored.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from html.parser import HTMLParser
from typing import Any

VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input",
        "link", "meta", "param", "source", "track", "wbr"}
# elements the editor never selects into — text is edited via set_text on the
# parent, and ops on these would corrupt the document
UNSELECTABLE = {"html", "head", "meta", "title", "style", "script", "link", "base"}

EDITOR_TAG = "script"
EDITOR_ATTR = "data-bird-editor"
# the theme's <style> marker. Unlike the bridge it is DESIGN CONTENT — the
# tokens the artboard is styled with — so _strip_editor_nodes must never
# touch it: it strips only EDITOR_TAG scripts carrying EDITOR_ATTR.
THEME_ATTR = "data-bird-theme"
# the polish pass's motion layer, marked like the theme. Also design content:
# a <style data-bird-motion> and a <script data-bird-motion> ride in every
# stored version and survive unwrap_editor into the handoff bundle. The
# script is the one place the no-script contract is relaxed — sanctioned in
# exactly one door (design_polish, showcase phase only), so the marker is
# also how the critic is handed just the motion layer as text.
MOTION_ATTR = "data-bird-motion"

# CDATA elements: their contents are code, not text, and must never be escaped
RAW_TEXT = {"script", "style"}


class Raw(str):
    """Markup emitted verbatim instead of escaped: the doctype, comments, and
    the contents of <script>/<style>. A str subclass, so every child check of
    the form `isinstance(c, str)` still holds and text_content still reads it.

    Everything else in a node's children is TEXT, and gets escaped on the way
    out — without this split a document round-trip turns `&lt;y&gt;` into a
    live `<y>` tag, and set_text becomes an html injection."""

    __slots__ = ()


class DomError(Exception):
    """A refusal both front ends show the same way."""


# eq=False: a node is a POSITION in a document, not a value — two <p>Hi</p> in
# different places are different nodes. The generated __eq__ would compare
# field by field, follow `parent` back up, and recurse without end the first
# time anything called children.index() on two similar-looking subtrees.
@dataclass(eq=False)
class Node:
    tag: str
    attrs: dict[str, str] = field(default_factory=dict)
    children: list["Node | str"] = field(default_factory=list)
    parent: "Node | None" = None

    def is_void(self) -> bool:
        return self.tag in VOID

    def child_elements(self) -> list["Node"]:
        return [c for c in self.children if isinstance(c, Node)]

    def text_content(self) -> str:
        out = []
        for c in self.children:
            out.append(c if isinstance(c, str) else c.text_content())
        return "".join(out)

    def outer_html(self) -> str:
        attrs = "".join(
            f' {k}' if v == "" else f' {k}="{_escape_attr(v)}"'
            for k, v in self.attrs.items()
        )
        if self.is_void():
            return f"<{self.tag}{attrs}>"
        inner = "".join(_render(c) for c in self.children)
        return f"<{self.tag}{attrs}>{inner}</{self.tag}>"


def _escape_text(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _escape_attr(s: str) -> str:
    return _escape_text(s).replace('"', "&quot;")


def _render(child: "Node | str") -> str:
    """One child, serialized: elements recurse, Raw goes out untouched, and
    everything else is text and gets escaped."""
    if isinstance(child, Node):
        return child.outer_html()
    return child if isinstance(child, Raw) else _escape_text(child)


class _Parser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.root = Node(tag="#root")
        self.stack: list[Node] = [self.root]

    def handle_starttag(self, tag, attrs):
        node = Node(tag=tag, attrs={k: (v or "") for k, v in attrs})
        node.parent = self.stack[-1]
        self.stack[-1].children.append(node)
        if tag not in VOID:
            self.stack.append(node)

    def handle_startendtag(self, tag, attrs):
        node = Node(tag=tag, attrs={k: (v or "") for k, v in attrs})
        node.parent = self.stack[-1]
        self.stack[-1].children.append(node)

    def handle_endtag(self, tag):
        for i in range(len(self.stack) - 1, 0, -1):
            if self.stack[i].tag == tag:
                del self.stack[i:]
                return
        # stray close tag: ignore — generated HTML is not guaranteed balanced

    def handle_decl(self, decl):
        # the doctype is not an element, but dropping it renders the artboard
        # in quirks mode the moment anything edits it
        self.stack[-1].children.append(Raw(f"<!{decl}>"))

    def handle_comment(self, data):
        self.stack[-1].children.append(Raw(f"<!--{data}-->"))

    def handle_data(self, data):
        if data:
            raw = self.stack[-1].tag in RAW_TEXT
            self.stack[-1].children.append(Raw(data) if raw else data)


def parse(html: str) -> Node:
    p = _Parser()
    p.feed(html)
    return p.root


def serialize(root: Node) -> str:
    """The document as HTML. The root is virtual; its children are the
    top-level nodes (doctype, html element)."""
    return "".join(_render(c) for c in root.children)


def _selector_path(node: Node) -> str:
    """`0>1>2` — index among the parent's ELEMENT children, from the document
    root (`<html>` is `0`). Never a tag name: resolve() int()s every segment."""
    parts: list[str] = []
    cur = node
    while cur is not None and cur.parent is not None and cur.tag != "#root":
        parent = cur.parent
        idx = parent.child_elements().index(cur)
        parts.append(str(idx))
        cur = parent
    return ">".join(reversed(parts))


def _by_id(root: Node, wanted: str) -> list[Node]:
    found: list[Node] = []

    def walk(node: Node) -> None:
        for c in node.child_elements():
            if c.attrs.get("id") == wanted:
                found.append(c)
            walk(c)

    walk(root)
    return found


def resolve(root: Node, selector: str) -> Node:
    """Find the element a selector points at. Raises DomError on a miss —
    the same refusal the page's iframe would give, so both front ends agree.

    Two spellings. The index path (`0>1>2`) is what the bridge and the
    outline print. `#id` names an element by its id when exactly one carries
    it — the form that survives an insert or delete ahead of the element,
    which shifts every index path behind it (the dominant edit refusal in the
    logged sessions). A leading `body>` is tolerated as the body's own path:
    the old schema text taught that spelling and models still reach for it."""
    if not isinstance(selector, str) or not selector.strip():
        raise DomError("no selector was sent")
    sel = selector.strip()
    if sel.startswith("#"):
        wanted = sel[1:].strip()
        if not wanted:
            raise DomError("bad selector '#': no id after the hash")
        hits = _by_id(root, wanted)
        if not hits:
            raise DomError(
                f"no element has id {wanted!r} — design_read shows the ids and "
                "index paths as the document stands")
        if len(hits) > 1:
            raise DomError(
                f"{len(hits)} elements carry id {wanted!r} — use the index path "
                "from design_read instead")
        node = hits[0]
        if node.tag in UNSELECTABLE:
            raise DomError(f"{node.tag} is not editable")
        return node
    if sel.lower().startswith("body"):
        rest = sel[4:]
        if rest == "" or rest.startswith(">"):
            sel = _selector_path(_find_body(root)) + rest
    cur: Node = root
    for part in sel.split(">"):
        try:
            idx = int(part)
        except ValueError:
            raise DomError(f"bad selector {selector!r}: {part!r} is not an index") from None
        kids = cur.child_elements()
        if idx < 0 or idx >= len(kids):
            raise DomError(
                f"selector {selector!r} no longer resolves — the document changed "
                "under it (stale page, or a regenerate landed mid-gesture)"
            )
        cur = kids[idx]
    if cur.tag in UNSELECTABLE:
        raise DomError(f"{cur.tag} is not editable")
    return cur


def _find_body(root: Node) -> Node:
    """The <body>: a direct child of the virtual root in a fragment, a child
    of <html> in a full document — the shape every design_create sends, and
    the one the old root-only scan missed, so an insert with no parent was
    refused on exactly the documents it was meant for."""
    for c in root.child_elements():
        if c.tag == "body":
            return c
        if c.tag == "html":
            for k in c.child_elements():
                if k.tag == "body":
                    return k
    raise DomError("the artboard has no <body> — it is not a document")


# ---- the op vocabulary ----
#
# set_style(selector, props) · set_text(selector, text) · insert(parent, html,
# position) · delete(selector) · duplicate(selector) · move(selector, new_parent,
# index). Every op returns its inverse as an op dict, so undo is replay, not
# snapshot diffing.

def _style_of(node: Node) -> dict[str, str]:
    raw = node.attrs.get("style", "")
    out: dict[str, str] = {}
    for decl in raw.split(";"):
        if ":" not in decl:
            continue
        k, v = decl.split(":", 1)
        out[k.strip().lower()] = v.strip()
    return out


def _write_style(node: Node, props: dict[str, str]) -> None:
    merged = _style_of(node)
    for k, v in props.items():
        if v is None or v == "":
            merged.pop(k, None)
        else:
            merged[str(k).strip()] = str(v).strip()
    if merged:
        node.attrs["style"] = "; ".join(f"{k}: {v}" for k, v in merged.items())
    else:
        node.attrs.pop("style", None)


def op_set_style(root: Node, op: dict[str, Any]) -> dict[str, Any]:
    node = resolve(root, op.get("selector", ""))
    props = op.get("props") or {}
    if not isinstance(props, dict) or not props:
        raise DomError("set_style needs a non-empty props object")
    before = _style_of(node)
    _write_style(node, props)
    inverse_props = {k: before.get(k, "") for k in props}
    return {"op": "set_style", "selector": op["selector"], "props": inverse_props}


def op_set_text(root: Node, op: dict[str, Any]) -> dict[str, Any]:
    node = resolve(root, op.get("selector", ""))
    text = str(op.get("text", ""))
    if node.child_elements():
        # replacing an element that has children would drop them; the editor
        # only text-edits leaf-ish elements
        raise DomError(
            "set_text only edits elements with no child elements — "
            "edit the inner text node directly"
        )
    before = node.text_content()
    node.children = [text]
    return {"op": "set_text", "selector": op["selector"], "text": before}


def op_insert(root: Node, op: dict[str, Any]) -> dict[str, Any]:
    parent_sel = str(op.get("parent") or "")
    parent = resolve(root, parent_sel) if parent_sel else _find_body(root)
    html = str(op.get("html") or "").strip()
    if not html:
        raise DomError("insert needs html")
    frag = parse(f"<div id='__frag'>{html}</div>")
    frag_root = frag.child_elements()[0]
    if len(frag.child_elements()) != 1 or frag_root.tag != "div" or frag_root.attrs.get("id") != "__frag":
        raise DomError("insert html did not parse")
    kids = [c for c in frag_root.children]
    if not kids:
        raise DomError("insert html has no content")
    pos = op.get("position")
    elements = parent.child_elements()
    if pos is None or pos == "end":
        index = len(elements)
        parent.children.extend(kids)
    else:
        try:
            index = int(pos)
        except (TypeError, ValueError):
            raise DomError(f"bad insert position {pos!r}") from None
        if index < 0 or index > len(elements):
            raise DomError(f"insert position {index} is out of range")
        # map element index to child-list index
        if index < len(elements):
            at = parent.children.index(elements[index])
            parent.children[at:at] = kids
        else:
            parent.children.extend(kids)
    for k in kids:
        if isinstance(k, Node):
            k.parent = parent
    return {"op": "delete", "selector": f"{_selector_path(kids[0]) if isinstance(kids[0], Node) else ''}"}


def op_delete(root: Node, op: dict[str, Any]) -> dict[str, Any]:
    node = resolve(root, op.get("selector", ""))
    parent = node.parent
    if parent is None:
        raise DomError("cannot delete the document root")
    index = parent.children.index(node)
    html = node.outer_html()
    parent.children.pop(index)
    return {"op": "insert", "parent": _selector_path(parent), "html": html,
            "position": _element_index(parent, index)}


def _element_index(parent: Node, child_list_index: int) -> int:
    """The element-index of the child at child_list_index (for re-insert)."""
    count = 0
    for i, c in enumerate(parent.children):
        if isinstance(c, Node):
            if i == child_list_index:
                return count
            count += 1
    return count


def op_duplicate(root: Node, op: dict[str, Any]) -> dict[str, Any]:
    node = resolve(root, op.get("selector", ""))
    parent = node.parent
    if parent is None:
        raise DomError("cannot duplicate the document root")
    import copy
    # deepcopy follows `parent`, so cloning a node would clone the entire
    # document upward; detach for the copy and put the link straight back
    detached, node.parent = node.parent, None
    try:
        clone = copy.deepcopy(node)
    finally:
        node.parent = detached
    idx = parent.children.index(node) + 1
    parent.children.insert(idx, clone)
    clone.parent = parent
    return {"op": "delete", "selector": _selector_path(clone)}


def _contains(ancestor: Node, node: Node) -> bool:
    """Is `node` the ancestor itself, or inside it? Mirrors the bridge's
    `el === np || el.contains(np)`."""
    cur: Node | None = node
    while cur is not None:
        if cur is ancestor:
            return True
        cur = cur.parent
    return False


def op_move(root: Node, op: dict[str, Any]) -> dict[str, Any]:
    node = resolve(root, op.get("selector", ""))
    old_parent = node.parent
    if old_parent is None:
        raise DomError("cannot move the document root")
    old_list_idx = old_parent.children.index(node)
    old_pos = _element_index(old_parent, old_list_idx)
    new_parent_sel = str(op.get("new_parent") or "")
    new_parent = resolve(root, new_parent_sel) if new_parent_sel else _find_body(root)
    if _contains(node, new_parent):
        # without this the node becomes its own parent and _selector_path spins
        # forever — the bridge refuses the same gesture (el === np || contains)
        raise DomError("cannot move an element into itself, or into its own child")
    index = op.get("index")
    old_parent.children.pop(old_list_idx)
    elements = new_parent.child_elements()
    if index is None:
        index = len(elements)
    else:
        try:
            index = int(index)
        except (TypeError, ValueError):
            raise DomError(f"bad move index {index!r}") from None
        index = max(0, min(index, len(elements)))
    if index < len(elements):
        at = new_parent.children.index(elements[index])
        new_parent.children.insert(at, node)
    else:
        new_parent.children.append(node)
    node.parent = new_parent
    return {"op": "move", "selector": op["selector"],
            "new_parent": _selector_path(new_parent), "index": index,
            "_from": {"parent": _selector_path(old_parent), "index": old_pos}}


OPS = {
    "set_style": op_set_style,
    "set_text": op_set_text,
    "insert": op_insert,
    "delete": op_delete,
    "duplicate": op_duplicate,
    "move": op_move,
}


def apply_op(root: Node, op: dict[str, Any]) -> dict[str, Any]:
    """Apply one op, returning its inverse. Raises DomError on any refusal."""
    name = str(op.get("op") or "")
    fn = OPS.get(name)
    if fn is None:
        raise DomError(f"unknown op {name!r} (expected one of: {', '.join(OPS)})")
    return fn(root, op)


# ---- wrap / unwrap: the editor script rides with the document ----

def wrap_editor(html: str, script: str) -> str:
    """Inject the editor script as the last child of <body>, marked with
    EDITOR_ATTR so unwrap can find it. The harness's copy is the WRAPPED
    version — selectors match what the iframe sees."""
    marker = f"{EDITOR_TAG} {EDITOR_ATTR}"
    if marker in html:
        return html  # already wrapped
    m = re.search(r"</body\s*>", html, re.IGNORECASE)
    tag = f"<{EDITOR_TAG} {EDITOR_ATTR}>{script}</{EDITOR_TAG}>"
    if m:
        return html[:m.start()] + tag + html[m.start():]
    return html + tag


def unwrap_editor(html: str) -> str:
    """Strip the editor script by parsing and re-serializing — never string
    surgery — so finalize hands the code harness a clean spec."""
    root = parse(html)
    _strip_editor_nodes(root)
    return serialize(root)


def _strip_editor_nodes(node: Node) -> None:
    keep = []
    for c in node.children:
        if isinstance(c, Node) and c.tag == EDITOR_TAG and EDITOR_ATTR in c.attrs:
            continue
        if isinstance(c, Node):
            _strip_editor_nodes(c)
        keep.append(c)
    node.children = keep


def inject_theme(html: str, css: str) -> str:
    """Insert the theme's tokens as `<style data-bird-theme>` — the FIRST
    child of <head>, so the document's own styles override them. Parse-based
    like wrap_editor, never string surgery, and idempotent: a theme style
    already present has its content replaced, not duplicated. A missing
    <head> is created (inside <html> when there is one). The result is design
    content: it rides in every stored version and unwrap_editor leaves it."""
    root = parse(html)
    # the parser root is virtual: in a full document <head> hangs off <html>,
    # not off the root — a fragment without <html> hangs it off the root
    html_el = next((c for c in root.child_elements() if c.tag == "html"), None)
    scope = html_el if html_el is not None else root
    head = next((c for c in scope.child_elements() if c.tag == "head"), None)
    if head is None:
        head = Node(tag="head")
        scope.children.insert(0, head)
        head.parent = scope
    style = next((c for c in head.child_elements()
                  if c.tag == "style" and THEME_ATTR in c.attrs), None)
    if style is None:
        style = Node(tag="style", attrs={THEME_ATTR: ""})
        head.children.insert(0, style)
        style.parent = head
    style.children = [Raw(css)] if css else []
    return serialize(root)


def inject_motion(html: str, css: str = "", script: str = "") -> str:
    """The polish pass's motion layer: `<style data-bird-motion>` at the end
    of <head> (after the theme's tokens — the polish is the last word on
    style) and `<script data-bird-motion>` at the end of <body>, BEFORE the
    editor bridge. Nothing is appended after the elements the selector paths
    point at, so no existing path shifts, and wrap_editor still lands the
    bridge last.

    Parse-based like every injection here, never string surgery, and
    idempotent the way inject_theme is: a re-polish replaces the marked nodes
    in place instead of stacking, and an empty part removes its node — a
    re-polish that passes only css takes the previous script back out."""
    root = parse(html)
    html_el = next((c for c in root.child_elements() if c.tag == "html"), None)
    scope = html_el if html_el is not None else root
    head = next((c for c in scope.child_elements() if c.tag == "head"), None)
    if head is None:
        head = Node(tag="head")
        scope.children.insert(0, head)
        head.parent = scope
    body = next((c for c in scope.child_elements() if c.tag == "body"), None)
    if body is None:
        # same refusal _find_body gives a fragment: a document with no body
        # is not something to hang motion off
        raise DomError("the artboard has no <body> — it is not a document")
    style = next((c for c in head.child_elements()
                  if c.tag == "style" and MOTION_ATTR in c.attrs), None)
    if css:
        if style is None:
            style = Node(tag="style", attrs={MOTION_ATTR: ""})
            head.children.append(style)
            style.parent = head
        style.children = [Raw(css)]
    elif style is not None:
        head.children.remove(style)
    # the bridge is wrap_editor's last child of <body>; the motion script
    # goes before it so the bridge stays last (and a missing bridge — an
    # unwrapped document — still appends at the end)
    bridge = next((c for c in body.child_elements()
                   if c.tag == EDITOR_TAG and EDITOR_ATTR in c.attrs), None)
    script_node = next((c for c in body.child_elements()
                        if c.tag == "script" and MOTION_ATTR in c.attrs), None)
    if script:
        if script_node is None:
            script_node = Node(tag="script", attrs={MOTION_ATTR: ""})
            at = body.children.index(bridge) if bridge is not None else len(body.children)
            body.children.insert(at, script_node)
            script_node.parent = body
        script_node.children = [Raw(script)]
    elif script_node is not None:
        body.children.remove(script_node)
    return serialize(root)


def motion_layer(html: str) -> str:
    """The motion layer as text — what the critic reads as the choreography,
    the way it reads the element outline. Empty when the artboard was never
    polished."""
    root = parse(html)
    found: list[str] = []

    def walk(node: Node) -> None:
        for c in node.child_elements():
            if MOTION_ATTR in c.attrs and c.tag in ("style", "script"):
                found.append(c.text_content())
            walk(c)

    walk(root)
    return "\n\n".join(part.strip() for part in found if part.strip())